### ISSUE TITLE
autocomplete errors out on clean install

### ISSUE THREAD

**Issue by shaksi** [mattweber/solr-for-wordpress#5]
search still works but the autocomplete shows error.
This is with a vanilla install of WP 3.2.1

`
[Sun Aug 28 19:10:45 2011] [error] [client 127.0.0.1] PHP Fatal error:  Uncaught exception 'Exception' with message '"404" Status: Not Found' in /Users/shaksi/Sites/wordpress/wp-content/plugins/solr-for-wordpress/Apache/Solr/Service.php:294\nStack trace:\n#0 /Users/shaksi/Sites/wordpress/wp-content/plugins/solr-for-wordpress/Apache/Solr/Service.php(934): Apache_Solr_Service->_sendRawGet('http://localhos...')\n#1 /Users/shaksi/Sites/wordpress/wp-content/plugins/solr-for-wordpress/solr-for-wordpress.php(1281): Apache_Solr_Service->search('post', 0, NULL, Array)\n#2 /Users/shaksi/Sites/wordpress/wp-content/plugins/solr-for-wordpress/solr-for-wordpress.php(1149): s4w_autocomplete('post', NULL)\n#3 [internal function]: s4w_template_redirect('')\n#4 /Users/shaksi/Sites/wordpress/wp-includes/plugin.php(405): call_user_func_array('s4w_template_re...', Array)\n#5 /Users/shaksi/Sites/wordpress/wp-includes/template-loader.php(7): do_action('template_redire...')\n#6 /Users/shaksi/Sites/wordpress/wp-blog-header.php(16): require_once('/Users/shaksi/S...')\n#7 /Users/shaksi/Sites/wordpress/index.php(17) in /Users/shaksi/Sites/wordpress/wp-content/plugins/solr-for-wordpress/Apache/Solr/Service.php on line 294, referer: http://wp.local/?s=post`

**Comment by bejean** [comment]
Shaksi what is the status for this issue ?

**Comment by dustinrue** [comment]
I would guess this is no longer an issue, it isn't failing for me anywhere

**Comment by mmccook** [comment]
This issue is caused by not having Spellcheck configured on Solr, atleast that was the solution for my error on autocompletes 404 and 400 errors.
